export const project_data = [
  {
    id: 0,
    img_url: `youtube.png`,
    title: `Youtube Clone`,
    time: `August 2023`,
    description: `Youtube clone was a tutorial to learn the positions in CSS and media quaries. Moreover, I learned how JS objects are used for and then I can store my data in JS objects array instead of adding data in each element.`,
    type: `HTML`,
    css: "CSS",
  },
  {
    id: 1,
    img_url: `discord.png`,
    title: `Discord Clone`,
    time: `August 2023`,
    description: `This is the first project that I built with React and simple CSS. But this ain't still responsive, aim for larger devices. 
    Cause I just built this clone discord to see how react components work.`,
    type: `React`,
    css: "CSS",
  },
  {
    id: 2,
    img_url: `calculator.png`,
    video_url: `calculator.mp4`,
    title: `simple calculator`,
    time: `october 2023`,
    description: `I think this is a project that every beginners should have.`,
    type: `React`,
    css: "Tailwind CSS",
  },
  {
    id: 3,
    img_url: `travel.png`,
    title: `my travel journal`,
    time: `september 2023`,
    description: `This platform serves as an online hub specifically designed for travelers to share their travel experiences through written blogs.`,
    type: `React`,
    css: "Tailwind CSS",
  },
  {
    id: 4,
    img_url: `agency.png`,
    title: `whale agency`,
    time: `October 2023`,
    description: `Whale Seaman Agency is an online platform dedicated to connecting job seekers with maritime employment opportunities. It serves as a valuable resource for individuals in search of seaman positions, offering a streamlined approach to finding their next job in the maritime industry.`,
    type: `React`,
    css: "Tailwind CSS",
  },
];
